version: '3'

services:
  # -- Bootstrap Node --
  bootstrap:
    build: .
    container_name: bootstrap
    # Συνδέουμε τον τοπικό φάκελο στο /app του container (bind mount)
    volumes:
      - .:/app
    # Ρυθμίζουμε περιβάλλον development για Flask
    environment:
      - IP=0.0.0.0
      - PORT=8000
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    command: >
      python app.py
      --ip bootstrap
      --port 8000
      --bootstrap
      --replication_factor 3
      --consistency_mode linearizability

  # - "- Node 1 --
  node1:
    build: .
    container_name: node1
    depends_on:
      - bootstrap
    volumes:
      - .:/app
    environment:
      - IP=node1
      - PORT=8001
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
    ports:
      - "8001:8001"
    command: >
      sh -c "sleep 1 && python app.py
      --ip node1
      --port 8001
      --bootstrap_ip bootstrap
      --bootstrap_port 8000 "

  # -- Node 2 --
  node2:
    build: .
    container_name: node2
    depends_on:
      - bootstrap
    volumes:
      - .:/app
    environment:
      - IP=node2
      - PORT=8002
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
    ports:
      - "8002:8002"
    command: >
      sh -c "sleep 2 && python app.py
      --ip node2
      --port 8002
      --bootstrap_ip bootstrap
      --bootstrap_port 8000 "

  # -- Node 3 --
  node3:
    build: .
    container_name: node3
    depends_on:
      - bootstrap
    volumes:
      - .:/app
    environment:
      - IP=node3
      - PORT=8003
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
    ports:
      - "8003:8003"
    command: >
      sh -c "sleep 3 && python app.py
      --ip node3
      --port 8003
      --bootstrap_ip bootstrap
      --bootstrap_port 8000 "

  # -- Node 4 --
  node4:
    build: .
    container_name: node4
    depends_on:
      - bootstrap
    volumes:
      - .:/app
    environment:
      - IP=node4
      - PORT=8004
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
    ports:
      - "8004:8004"
    command: >
      sh -c "sleep 4 && python app.py
      --ip node4
      --port 8004
      --bootstrap_ip bootstrap
      --bootstrap_port 8000 " 
    
  # -- Node 5 --
  node5:
    build: .
    container_name: node5
    depends_on:
      - bootstrap
    volumes:
      - .:/app
    environment:
      - IP=node5
      - PORT=8005
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
    ports:
      - "8005:8005"
    command: >
      sh -c "sleep 5 && python app.py
      --ip node5
      --port 8005
      --bootstrap_ip bootstrap
      --bootstrap_port 8000 "
  
  # -- Node 6 --
  node6:
    build: .
    container_name: node6
    depends_on:
      - bootstrap
    volumes:
      - .:/app
    environment:
      - IP=node6
      - PORT=8006
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
    ports:
      - "8006:8006"
    command: >
      sh -c "sleep 6 && python app.py
      --ip node6
      --port 8006
      --bootstrap_ip bootstrap
      --bootstrap_port 8000 "
    
  # -- Node 7 --
  node7:
    build: .
    container_name: node7
    depends_on:
      - bootstrap
    volumes:
      - .:/app
    environment:
      - IP=node7
      - PORT=8007
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
    ports:
      - "8007:8007"
    command: >
      sh -c "sleep 7 && python app.py
      --ip node7
      --port 8007
      --bootstrap_ip bootstrap
      --bootstrap_port 8000 "
    